### ISSUE TITLE
Star file format for relion 3.1.2

### ISSUE THREAD

**Issue by rezaparaancryoem** [teamtomo/teamtomo-site-archive#43]
The star file created by warp is not enough for relion 3.1.2 refinement. Without the _optics table, the refinement job terminates. I used the `relion_convert_star `to reformat the star file. But that is not enough, I manually added columns 6 and 7. This is what the beginning of the star file looks like:
```
data_optics

loop_ 
_rlnOpticsGroup #1 
_rlnOpticsGroupName #2 
_rlnImagePixelSize #3 
_rlnImageSize #4 
_rlnImageDimensionality #5
_rlnVoltage #6
_rlnSphericalAberration #7 
           1 opticsGroup1     5.000000           64            3        300.00  2.7
```

**Comment by alisterburt** [comment]
hmm, not sure what the best way to deal with this is, a new version of warp is on the way which should generate 3.1/4.0 style star files so it will become a non-issue

**Comment by alisterburt** [comment]
this came up today https://gist.github.com/alisterburt/2ea6ad5b83299abfe03423f0e57fbb52 is a simple workaround script

**Comment by brisvag** [comment]
Should we add the script to the guide?

**Comment by alisterburt** [comment]
could do! Originally stayed away from custom python scripts because that would mean learning how to run them but could be added for sure

**Comment by brisvag** [comment]
We can always add it as a "this is how we did it" ina  side bar. Better something that requires some learning that somethign that just doesn't work :P
