### ISSUE TITLE
Check Radial distribution code issue

### ISSUE THREAD

**Issue by benjaminpreece** [teamtomo/teamtomo-site-archive#51]
Afternoon!

I have been following the team tomo tutorials for subtomogram averaging, and they have been extremely helpful! I'm currently attempting to apply my average to some tomograms in order to see how the HIV 1 gag lattice of my virions looks. I'm having trouble running the code for checking the radial distribution of the particles. I get the following error when I try to run it. 

unrecognized function or variable 'dtneighbours_in_range'.

Error in check_radial_distribution (line 15)
    n_neighbours = dtneighbours_in_range(table, min_dist, max_dist);

Is there a function I'm missing, or is the issue the version of dynamo/matlab that I'm using?

Thanks for the help!

**Comment by alisterburt** [comment]
Hey Benjamin! The script you are missing is here https://github.com/teamtomo/teamtomo.github.io/tree/master/walkthroughs/EMPIAR-10164/scripts

Glad you are finding things useful, good luck and have fun :-)

**Comment by alisterburt** [comment]
Todo: make script location more obvious in the HIV walkthrough
