### ISSUE TITLE
Broken link in /walkthroughs/EMPIAR-10164/ini-model.md

### ISSUE THREAD

**Issue by dmichalak** [teamtomo/teamtomo-site-archive#53]
Hello,

I'm working through the tutorial and came across a broken link in this sentence:

The Jiang lab at Purdue University have a CTF simulation [web app](https://ctf-simulation.herokuapp.com/) which is useful for visualising the effect of defocus on the CTF.

The correct url is https://ctfsimulation.herokuapp.com/
It also looks like they're discontinuing this url and moving to https://jianglab-ctfsimulation-streamlit-app-of60di.streamlitapp.com/

Best,
Dennis

PS: I'm relatively new to github and wasn't sure if there was a quicker way to suggest this edit than through Issues.

**Comment by alisterburt** [comment]
Thank you for taking the time to raise an issue @dmichalak ! I've updated the link to a different (but similar) web app from the RELION team in #54
