### ISSUE TITLE
Walkthrough: EMPIAR-10164 (HIV VLPs) - M cannot read RELION 3.1+ .star files

### ISSUE THREAD

**Issue by dmichalak** [teamtomo/teamtomo-site-archive#57]
While working through https://teamtomo.org/walkthroughs/EMPIAR-10164/m.html, I found that M would not accept the `*_data.star` from the RELION refinement. I successfully worked around this by following the instructions here: https://groups.google.com/g/warp-em/c/uAlXyZkCsbc/m/qR8idaUhCQAJ

I think this is what `relion_star_downgrade` does. The output file generated still cannot be found by M, however, because the file name is `run_iter##_data_rln3.0.star` but M will only look for files with `*_data.star`.

**Proposed solution:**

Add text to the M walkthrough page around 
"Provide this mask to M, and then select the final particle positions (e.g: run_it019_data.star) as the input for particle poses. Click FINISH to generate the new species."
that explains the issue and how to fix it.
e.g.,
1) Run `relion_star_downgrade -s run_it019_data.star` 
2) Rename the output file from `run_it019_data_rln3.0.star` to `rln3.0_run_it019_data.star` so M can find the file and prevent the original run_it019_data.star from being overwritten.

**Comment by brisvag** [comment]
Oh, that's annoying! Thanks for pointing this out @dmichalak. Do you want to make a small PR with that addition yourself or do you prefer I take care of it? :)

**Comment by dmichalak** [comment]
I'll have a go at it!

**Comment by dmichalak** [comment]
I've made a small pull request and am closing this issue.
