### ISSUE TITLE
Will you accept a guide about processing tomo dataset using Scipion tomo and the integrted software..?

### ISSUE THREAD

**Issue by pconesa** [teamtomo/teamtomo-site-archive#60]
Hi, we are close to release the tomography plugins and were thinking to document here the process to HIV dataset 100% inside scipion?

**Comment by alisterburt** [comment]
Hey @pconesa - that would be really great! Thank you for reaching out first and do let me know if you need any help with the infrastructure.

I am looking to rework the site in the near future but as long as your documentation is in markdown any updates will be easy and I will do them myself 🙂 

Have fun processing!

**Comment by brisvag** [comment]
Awesome, would love to see more 0 to 100% guides with different pipelines! Happy to help too :muscle:

**Comment by pconesa** [comment]
Ok, thanks... will come back probably with some PR!
